-- MySQL Script generated by MySQL Workbench
-- Sun Nov  5 13:24:18 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE DATABASE `web`;
use `web`;
-- -----------------------------------------------------
-- Table `pravo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pravo` ;

CREATE TABLE IF NOT EXISTS `pravo` (
  `id` SMALLINT NOT NULL,
  `nazev` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_czech_ci;


-- -----------------------------------------------------
-- Table `uzivatel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uzivatel` ;

CREATE TABLE IF NOT EXISTS `uzivatel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `jmeno` VARCHAR(50) NOT NULL,
  `prijmeni` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `heslo` VARCHAR(60) NOT NULL,
  `okres` VARCHAR(50) NOT NULL,
  `mesto` VARCHAR(50) NOT NULL,
  `ulice` VARCHAR(50) NOT NULL,
  `cp` SMALLINT NOT NULL,
  `psc` INT NOT NULL,
  `o_mne` TEXT NULL,
  `id_pravo` SMALLINT NOT NULL,
  PRIMARY KEY (`id`, `id_pravo`),
  INDEX `fk_uzivatel_pravo1_idx` (`id_pravo` ASC),
  CONSTRAINT `fk_uzivatel_pravo1`
    FOREIGN KEY (`id_pravo`)
    REFERENCES `pravo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_czech_ci;


-- -----------------------------------------------------
-- Table `objednavka`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objednavka` ;

CREATE TABLE IF NOT EXISTS `objednavka` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dokoncena` TINYINT NOT NULL,
  `datum` DATE NOT NULL,
  `id_uzivatel` INT NOT NULL,
  PRIMARY KEY (`id`, `id_uzivatel`),
  INDEX `fk_objednavka_uzivatel1_idx` (`id_uzivatel` ASC),
  CONSTRAINT `fk_objednavka_uzivatel1`
    FOREIGN KEY (`id_uzivatel`)
    REFERENCES `uzivatel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_czech_ci;


-- -----------------------------------------------------
-- Table `produkt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `produkt` ;

CREATE TABLE IF NOT EXISTS `produkt` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(50) NOT NULL,
  `cena` INT NOT NULL,
  `uskladneno_ks` INT NOT NULL,
  `foto` VARCHAR(50) NULL,
  `popis` TEXT NULL,
  `odstraneno` SMALLINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_czech_ci;


-- -----------------------------------------------------
-- Table `obsahuje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `obsahuje` ;

CREATE TABLE IF NOT EXISTS `obsahuje` (
  `id_objednavka` INT NOT NULL,
  `id_produkt` INT NOT NULL,
  `pocet_ks` SMALLINT NOT NULL,
  PRIMARY KEY (`id_objednavka`, `id_produkt`),
  INDEX `fk_produkt_has_objednavka_objednavka1_idx` (`id_objednavka` ASC),
  INDEX `fk_produkt_has_objednavka_produkt1_idx` (`id_produkt` ASC),
  CONSTRAINT `fk_produkt_has_objednavka_produkt1`
    FOREIGN KEY (`id_produkt`)
    REFERENCES `produkt` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produkt_has_objednavka_objednavka1`
    FOREIGN KEY (`id_objednavka`)
    REFERENCES `objednavka` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_czech_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `pravo`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `pravo` (`id`, `nazev`) VALUES (1, 'SuperAdmin');
INSERT INTO `pravo` (`id`, `nazev`) VALUES (2, 'Admin');
INSERT INTO `pravo` (`id`, `nazev`) VALUES (3, 'Dodavatel');
INSERT INTO `pravo` (`id`, `nazev`) VALUES (4, 'Konzument');

COMMIT;


-- -----------------------------------------------------
-- Data for table `uzivatel`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `uzivatel` (`id`, `jmeno`, `prijmeni`, `email`, `heslo`, `okres`, `mesto`, `ulice`, `cp`, `psc`, `o_mne`, `id_pravo`) VALUES (1, 'Karel', 'Novák', 'superadmin@zcu.cz', '$2y$10$FGXHY0lBvchPxX2NqjuCgeNVz0BZ9.cCwgLrc3zuJjHp8Dj/CDIYW', 'Plzeň-město', 'Plzeň', 'Technická', 8, 32000, '<p>Jsem <span style=\"font-size:24px;\"><b><i>﻿SUPERADMIN </i></b></span>této stránky.<br /></p>', 1);
INSERT INTO `uzivatel` (`id`, `jmeno`, `prijmeni`, `email`, `heslo`, `okres`, `mesto`, `ulice`, `cp`, `psc`, `o_mne`, `id_pravo`) VALUES (2, 'Tomáš', 'Novotný', 'admin@zcu.cz', '$2y$10$1hOLVrimQ9APC2AnFmPY1.jqYDevUGGhW/V16MYKTabMEFgIa8TVi', 'Ústí nad Labem', 'Ústí nad Labem', 'Ústecká', 67, 40001, NULL, 2);
INSERT INTO `uzivatel` (`id`, `jmeno`, `prijmeni`, `email`, `heslo`, `okres`, `mesto`, `ulice`, `cp`, `psc`, `o_mne`, `id_pravo`) VALUES (3, 'Alexander', 'Rychlý', 'dodavatel@zcu.cz', '$2y$10$pXF57od0hAfBBCRxyMAOJe5qqviv.QyNKk1VEVBAKO5.dHqjupMXK', 'Praha', 'Praha', 'Karlovarská', 13, 11000, NULL, 3);
INSERT INTO `uzivatel` (`id`, `jmeno`, `prijmeni`, `email`, `heslo`, `okres`, `mesto`, `ulice`, `cp`, `psc`, `o_mne`, `id_pravo`) VALUES (4, 'Petra', 'Parkerová', 'konzument@zcu.cz', '$2y$10$slb/fSwiKeDMBwUIRkANf.dFTWzXlLV7PKOpP/3sv4IjTNvx6GhAS', 'Klatovy', 'Klatovy', 'Národních mučedníků', 305, 33902, NULL, 4);

COMMIT;


-- -----------------------------------------------------
-- Data for table `produkt`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `produkt` (`id`, `nazev`, `cena`, `uskladneno_ks`, `foto`, `popis`,`odstraneno`) VALUES (1, 'BBQ Burger', 129, 5, 'bbq-burger.png', 'Je vyroben z hovězího masa a je ochucen BBQ omáčkou. Může být doplněn o další ingredience, jako je slanina, sýr, cibule a rajčata.', 0);
INSERT INTO `produkt` (`id`, `nazev`, `cena`, `uskladneno_ks`, `foto`, `popis`,`odstraneno`) VALUES (2, 'Beef Burger', 139, 5, 'beef-burger.png', 'Obsahuje hovězí maso a může být doplněn o další ingredience, jako je sýr, cibule a rajčata.', 0);
INSERT INTO `produkt` (`id`, `nazev`, `cena`, `uskladneno_ks`, `foto`, `popis`,`odstraneno`) VALUES (3, 'Grand Burger', 119, 5, 'grand-burger.png', 'Tento burger obsahuje hovězí maso, slaninu, sázené vejce, karamelizovanou cibuli, BBQ omáčku a tatarskou omáčku.', 0);
INSERT INTO `produkt` (`id`, `nazev`, `cena`, `uskladneno_ks`, `foto`, `popis`,`odstraneno`) VALUES (4, 'Cheese Burger', 109, 5, 'cheese-burger.png', 'Uvnitř totoho burgeru se nachází hovězí maso a sýr. Může být doplněn o další ingredience, jako jsou cibule a rajčata.', 0);
INSERT INTO `produkt` (`id`, `nazev`, `cena`, `uskladneno_ks`, `foto`, `popis`,`odstraneno`) VALUES (5, 'Chicken Burger', 145, 5, 'chicken-burger.png', 'Tento burger obsahuje kuřecí maso a může být doplněn o další ingredience, jako jsou sýr, cibule a rajčata.', 0);
INSERT INTO `produkt` (`id`, `nazev`, `cena`, `uskladneno_ks`, `foto`, `popis`,`odstraneno`) VALUES (6, 'Vegetarian Burger', 105, 5, 'vegetarian-burger.png', 'Daný burger neobsahuje maso a může být vyroben z různých rostlinných ingrediencí, jako jsou fazole, quinoa nebo tofu.', 0);
INSERT INTO `produkt` (`id`, `nazev`, `cena`, `uskladneno_ks`, `foto`, `popis`,`odstraneno`) VALUES (7, 'Kola', 39, 5, 'kola.png', '0.5 l', 0);
INSERT INTO `produkt` (`id`, `nazev`, `cena`, `uskladneno_ks`, `foto`, `popis`,`odstraneno`) VALUES (8, 'Voda', 20, 5, 'voda.png', '0.5 l', 0);
INSERT INTO `produkt` (`id`, `nazev`, `cena`, `uskladneno_ks`, `foto`, `popis`,`odstraneno`) VALUES (9, 'Džus', 29, 5, 'dzus.png', '0.5 l', 0);
INSERT INTO `produkt` (`id`, `nazev`, `cena`, `uskladneno_ks`, `foto`, `popis`,`odstraneno`) VALUES (10, 'Hranolky', 45, 5, 'hranolky.jpg', '150 g', 0);
INSERT INTO `produkt` (`id`, `nazev`, `cena`, `uskladneno_ks`, `foto`, `popis`,`odstraneno`) VALUES (11, 'Kečup', 29, 5, 'kecup.png', '20 ml', 0);
COMMIT;